### ISSUE TITLE
Stitchdata not syncing all pipedrive columns to data.world

### ISSUE THREAD

**Issue by vbchambers** [stitchdata/docs#182]
Hi - I've added new custom fields into pipedrive persons (People); however it doesn't seems that stitchdata is grabbing these fields because I don't see them show up in data.world.  for example, the field 7acf707bd7373a4a9badc0b425adc62efd96ff9a is not coming through.

**Comment by dylan-stitch** [comment]
Hi @vbchambers,

Stitch's support team will be the best resource for troubleshooting any behavior with Stitch Certified integrations or answering product questions. For Community integrations like Pipedrive, you'll want to head over to the Singer repository for the integration itself (which can be [found here for Pipedrive](https://github.com/singer-io/tap-pipedrive)). This repo handles questions and issues pertaining specifically to Stitch Documentation and we're happy to help if that's what you need.

You can reach our support team through in-app chat or by emailing help@stitchdata.com. I'm going to close this for now, but feel free to post questions or feedback about the docs here in the future.
