### ISSUE TITLE
Google Analytics integration data discrepancy

### ISSUE THREAD

**Issue by rafaelmnatali** [stitchdata/docs#206]
Hi there,

I created an integration from Google analytics to PostgreSQL and noticed a discrepancy in the "sessions" data. 

When I use Google's Query Explorer to get the exactly same metrics I'm using in my integrations the number is different from what I have in my database. In my database is always the number is always higher which leads to different numbers viewing from Google's dashboard and from my Grafana's dashboards.

For example on 11/22 Google show me 259 against 275 sessions in the database. 

metrics: 

dimensions = ga:sessionCount
metrics = ga:sessions

dimensions = ga:sessionDurationBucket
metrics = ga:avgSessionDuration

dimensions = ga:pagePath
metrics = ga:pageviews

[Google Metrics.xlsx](https://github.com/stitchdata/docs/files/2611180/Google.Metrics.xlsx)

Thx for your help.

**Comment by erinkcochran87** [comment]
Hi there @rafaelmnatali! Stitch's support team is the best resource for troubleshooting any behavior or answering product questions. This repo handles questions and issues pertaining to the [Stitch Docs](https://www.stitchdata.com/docs) - happy to help if that's what you need.

You can reach our support team through in-app chat or by emailing help@stitchdata.com. I'm going to close this for now, but feel free to post questions or feedback about the docs here in the future.

**Comment by rafaelmnatali** [comment]
OK. I'll contact the support. 

thanks for the info.
