### ISSUE TITLE
Refactor function

### ISSUE THREAD

**Issue by luandy64** [stitchdata/docs#286]
Seems like this function should assert that `type` looks a certain way and that the object contains `properties` otherwise throw. I'm not sure the exception handling is actually hit, but rather the first error statement gets printed.

https://github.com/stitchdata/docs/blob/b6d8e72a33c7add4b9900edf4e42b0df7c04396b/scripts/tap-generate-docs/src/tap_generate_docs.clj#L193-L202

**Comment by erinkcochran87** [comment]
@luandy64 Should this be kept open? I think this was resolved in the last round of tap-generate-docs fixes.

**Comment by luandy64** [comment]
I think we can close it. If the tool works right now, then my point here doesn't matter
