### ISSUE TITLE
Stitch doesn't support using the South America destination for Google Cloud destinations

### ISSUE THREAD

**Issue by danilolessa** [stitchdata/docs#310]

**Comment by erinkcochran87** [comment]
Hi there @danilolessa! Stitch's support team is the best resource for getting answers to product questions or filing feedback about Stitch. This repo handles questions and issues pertaining to the Stitch Docs - happy to help if that's what you need.

You can reach our support team through in-app chat or by emailing help@stitchdata.com. I'm going to submit feedback for this feature to the product team for you and close this out for now. Feel free to post questions or feedback about the docs here in the future.
