### ISSUE TITLE
Adwords - Duplicate rows

### ISSUE THREAD

**Issue by asitmonty** [stitchdata/docs#312]
I am running a Stitch based Adwords extraction to Redshift.
I noticed that on my Call Metrics table one of the source rows is replicated every run, thereby inflating the real value. 
The attached file has all instances of this duplicate row. The only differentiating fields for these rows is the default _sdc_ rows that Stitch uses.
[duplicate_stitch.xlsx](https://github.com/stitchdata/docs/files/3211378/duplicate_stitch.xlsx)

I haven't made any settings changes to the report extract so there might be something that I am missing. I haven't checked this with other tables yet. 
Please help fix this.

**Comment by erinkcochran87** [comment]
Hi there @asitmonty! Stitch's support team is the best resource for troubleshooting any behavior or answering product questions. This repo handles questions and issues pertaining to the Stitch Docs - happy to help if that's what you need.

You can reach our support team through in-app chat or by emailing help@stitchdata.com. I'm going to close this for now, but feel free to post questions or feedback about the docs here in the future.

**Comment by Jurgem** [comment]
@asitmonty i don't know if you solve this issue, but is not an issue and this is explained into the docs of Stitch Google Ads:

[https://www.stitchdata.com/docs/integrations/saas/google-ads#query-for-the-latest-data](url)


i have the same "problem" and that solve it
