### ISSUE TITLE
Destination Google cloud storage

### ISSUE THREAD

**Issue by Mani3274** [stitchdata/docs#352]
Hi, 

Does stitch support Google cloud storage (GCS) as a destination? If not, is it on your roadmap?

While incase of BigQuery destination, I see it uses GCS temporarily to hold the data. Can we configure time/quantity to hold the data before moving to Big query?

**Comment by erinkcochran87** [comment]
Hi there @Mani3274, Stitch's support team is the best resource for troubleshooting any behavior or answering product questions. You can reach our support team through in-app chat or by emailing help@stitchdata.com.

If you have questions or feedback on the [Stitch Docs](https://www.stitchdata.com/docs), though, I'd be happy to assist!
