### ISSUE TITLE
Geometry data type PostgreSQL integration

### ISSUE THREAD

**Issue by JeremyLG** [stitchdata/docs#358]
Do you know if you plan to support the Geometry data type in PostgreSQL ? It' s a point describing the latitude and longitude.

Thanks for your answer

**Comment by luandy64** [comment]
Just to clarify, you mean support for extracting Geometry fields from a Postgres source, correct?

**Comment by luandy64** [comment]
If so, I recommend you open an issue on the [tap-postgres](https://github.com/singer-io/tap-postgres) repo instead of here.
