### ISSUE TITLE
Add date as a dimension to Google E-Commerce integration

### ISSUE THREAD

**Issue by dctanugi** [stitchdata/docs#383]
It's hard to derive useful insights from the Google E-Commerce integration (e.g. from which sources are the majority of our transactions coming?) without a time dimension. Each transaction has a date associated with it, so it would be valuable to add the transaction date to the schema.

**Comment by erinkcochran87** [comment]
Hi there @dctanugi , Stitch's support team is the best resource for troubleshooting any behavior or answering product questions. You can reach our support team through in-app chat or by emailing help@stitchdata.com.

If you have questions or feedback on the [Stitch Docs](https://www.stitchdata.com/docs), though, I'd be happy to assist!
