### ISSUE TITLE
Missing Required Parameter when connecting to SQL Server

### ISSUE THREAD

**Issue by sstaton89** [stitchdata/docs#386]
Hi,

When set up to integrate with SQL server I'm getting the following: 

"user "[REDACTED]"} is missing a required parameter"

All of the details I'm using are correct. What could the problem be?

**Comment by erinkcochran87** [comment]
Hi there @sstaton89, Stitch's support team is the best resource for troubleshooting any behavior or answering product questions. You can reach our support team through in-app chat or by emailing help@stitchdata.com.

If you have questions or feedback on the [Stitch Docs](https://www.stitchdata.com/docs), though, I'd be happy to assist!
