### ISSUE TITLE
BigQuery has reported an error, but the docs are not helpful with what to do next

### ISSUE THREAD

**Issue by edhgoose** [stitchdata/docs#388]
Google Cloud is currently suffering from a number of issues:

https://status.cloud.google.com/

And we're loading some data via Stitch into BigQuery. 

We've had the following error:

<img width="745" alt="Stitch_-_Notifications" src="https://user-images.githubusercontent.com/1108173/68607441-888a4000-04a8-11ea-9985-6325ba577502.png">

And the links send us to this page:

https://www.stitchdata.com/docs/troubleshooting/destinations/destination-data-loading-errors

Which doesn't have any context about BigQuery.

My suspicion is that this issue will resolve itself when BigQuery comes back up, but until then, the Stitchdata status dashboard (https://status.stitchdata.com/) says everything is ok, and I'd love some reassurance that either everything _is_ ok, or what to do to verify if it is / isn't ok.

Can the docs be improved to explain what to do in this scenario?

Thanks!
 
(p.s. your documentation is generally fantastic and an inspiration. Thank you).

**Comment by erinkcochran87** [comment]
Hey there, @edhgoose!

Thanks for bringing this up! On Stitch's end, this error typically means that we received what we thought was a JSON-formatted error from Google, but couldn't parse it. This lead to the `Invalid JSON response from Google` message you received in the Stitch app.

As you said, I see that [BigQuery had some service issues earlier today](https://status.cloud.google.com/). Everything has been fine on our end, but the Stitch Support team would be better situated to dig into this more - feel free to reach out to them by logging into your account.

As for the docs, I think I can put something about this in there - though I hope we will be able to have Stitch provide a more helpful message in-app in the future :) I'm glad you find the docs useful, and if you have any other feedback in the future, please let us know.

Thanks again!
Erin
