### ISSUE TITLE
Bad data replicating Recurly

### ISSUE THREAD

**Issue by sreekotay** [stitchdata/docs#390]
In order to have the correct data sync for line item invoices from recurly, "X-Api-Version: 2.22" must be specified as an HTTP header.  Without this, recurly returns the data in a kind of "quirks" mode, where it returns incorrect data.

Could this be corrected in stitch?  or specified as an additional parameter in the recurly/stitch integration?

**Comment by erinkcochran87** [comment]
Hi there @sreekotay, Stitch's support team is the best resource for troubleshooting any behavior or answering product questions. You can reach our support team through in-app chat or by emailing `help@stitchdata.com`.

If you have questions or feedback on the [Stitch Docs](https://www.stitchdata.com/docs), though, I'd be happy to assist!

**Comment by sreekotay** [comment]
Gotcha - thanks!

**Comment by sreekotay** [comment]
I've tried help@stitchdata.com a few times and despite being a paying
customer, have gotten no response.  Is there another channel I can use?
Thanks!
Sree

**Comment by erinkcochran87** [comment]
Hey @sreekotay - I looked into this. It looks like Stitch Support last sent you a message on November 22.

It looks like there might be two Stitch accounts associated with two email addresses of yours. Can you please log into both of them and see if you see a response from Stitch Support? It's possible you were logging into one account and expecting to see something, but the support conversation was taking place in the other account.
