### ISSUE TITLE
Actions from automations?

### ISSUE THREAD

**Issue by isacolick** [stitchdata/docs#397]
Do opens/clicks from automations appear in reports_email_activity? I don't think I see this click data in my table.

**Comment by luandy64** [comment]
Is this a mailchimp question?

**Comment by erinkcochran87** [comment]
Hi there @isacolick, Stitch's support team is the best resource for troubleshooting any behavior or answering product questions. You can reach our support team through in-app chat or by emailing help@stitchdata.com.

If you have questions or feedback on the [Stitch Docs](https://www.stitchdata.com/docs), though, I'd be happy to assist!
