### ISSUE TITLE
wrong record in _sdc_batched_at

### ISSUE THREAD

**Issue by deniznurr** [stitchdata/docs#401]
Hello, 
I found some weird record in my DWH. Result of my research i found an error in the _sdc_batched_at column. in that my case there isn't problem in _sdc_sequence column but in _sdc_batched_at column i think it might be an issue. I added to below an image about my table result. You can see last sdc_sequence number true but last sdc_batched_at  row is wrong!

Could you help me with this issue?

![image](https://user-images.githubusercontent.com/58939801/70905012-dc41f900-2013-11ea-9bf9-db449d8a569c.png)

**Comment by erinkcochran87** [comment]
Hi there @deniznurr, Stitch's support team is the best resource for troubleshooting any behavior or answering product questions. You can reach our support team through in-app chat or by emailing help@stitchdata.com.

If you have questions or feedback on the [Stitch Docs](https://www.stitchdata.com/docs), though, I'd be happy to assist!
