### ISSUE TITLE
"ERROR: permission denied for database x" for AWS Postgres destination

### ISSUE THREAD

**Issue by NickKellett** [stitchdata/docs#406]
Hi, I am trying to import Harvest data into a Postgres db destination on AWS and I get permission errors (connection to the db works fine). 

When trying to follow the setup permissions I was unable to run this command `GRANT SELECT ON ALL TABLES IN SCHEMA pg_catalog TO stitch;` because it generated the following error: "permission denied for table pg_statistic". The documentation mentions that Stitch first tries to read the pg_catalog schema before uploading, so I imagine this is the source of the original error. But I'm not sure what else to try get this to work.

**Comment by erinkcochran87** [comment]
Hi there @NickKellett, Stitch's support team is the best resource for troubleshooting any behavior or answering product questions. You can reach our support team through in-app chat or by emailing help@stitchdata.com.

If you have questions or feedback on the [Stitch Docs](https://www.stitchdata.com/docs), though, I'd be happy to assist!

**Comment by NickKellett** [comment]
Sorry, the troubleshooting page seemed to imply this was the place to open an issue - I'll reach out to them. Thanks!

**Comment by erinkcochran87** [comment]
No problem!
