### ISSUE TITLE
Tables not replicating

### ISSUE THREAD

**Issue by dwalshcst** [stitchdata/docs#42]
Hi - I have a table checked to get tracked (email_events) but I'm not seeing it in my Loading Reports and it's been 2 days. Can you help me?

**Comment by dylan-stitch** [comment]
Hi there @dwalshcst , Stitch's support team is the best resource for troubleshooting any behavior or answering product questions.

You can reach our support team through in-app chat or by emailing help@stitchdata.com.

**Comment by erinkcochran87** [comment]
Thanks for responding, @dylan-stitch!

@dwalshcst, this repo handles questions and issues pertaining to the [Stitch Docs](https://www.stitchdata.com/docs) - happy to help if that's what you need. To diagnose the issue with the `email_events` table not being loaded, please reach out to our support team as Dylan suggested.

I'm going to close this for now, but feel free to post questions or feedback about the docs here in the future.
