### ISSUE TITLE
Force append only incremental update on Postgres destination

### ISSUE THREAD

**Issue by ChrisCalculus** [stitchdata/docs#48]
Hi there,

the [docs](https://www.stitchdata.com/docs/data-structure/postgresql-data-loading-behavior#a-table-with-a-single-primary-key-is-synced) for a Postgres destination state, when syncing a table with a single Primary Key:

`If using Incremental Replication, data will be de-duped based on the Primary Key column and upserted into the table.`

The upsert prevents me from reporting incremental changes to a data object/record over time, as a single record just gets updated instead of adding additional entries for any changes occurring between sync intervals. E.g. image I would want to report the changes to a 'project' record in the table 'Projects.

How can I force the append only incremental updates as described [here](https://www.stitchdata.com/docs/replication/replication-methods#append-only-incremental-replication).

Thanks,

**Comment by dylan-stitch** [comment]
Followed up with @ChrisCalculus through Stitch's support channels.

For future reference, Stitch's support team is the best resource for troubleshooting any behavior or answering product questions.

Users can reach our support team through in-app chat or by emailing help@stitchdata.com.
