### ISSUE TITLE
Redshift Documentation

### ISSUE THREAD

**Issue by AndrewHannigan** [stitchdata/docs#513]
Redshift documentation references commands that are only available via psql tool (`\d+`), but suggests connecting to redshift via any arbitrary sql client.  Docs should be updated to specify that connection needs to be made via psql, or sql commands should be updated so that they can be executed by any sql client.

https://www.stitchdata.com/docs/destinations/amazon-redshift/apply-encodings-sort-dist-keys-redshift#retrieve-table-schema

**Comment by erinkcochran87** [comment]
Hey @AndrewHannigan! Thanks for pointing this out. I'm going to create a ticket for my team to address this - I'll update you here when we start work and when we close it.

**Comment by erinkcochran87** [comment]
Hey @AndrewHannigan - I've got the ticket for this and will be addressing it today. I'll update here again when I'm finished.

**Comment by erinkcochran87** [comment]
The changes for this have since been released- closing!
