### ISSUE TITLE
Connection refused [Postgresql]

### ISSUE THREAD

**Issue by jrdnlowry** [stitchdata/docs#537]
I'm trying to integrate postgresql with stich data and I'm having issues establishing a connection.

I'm currently encountering this error "2020-08-19 11:39:46,651Z   main - INFO Exit status is: Discovery failed with code 1 and error message: "could not connect to server: Connection refused"."

Within my postgresql.conf file the listen_addresses is set to '*' by default. Is this correct or do I need to explicitly allow access to these IP addresses:

- 52.23.137.21/32
- 52.204.223.208/32
- 52.204.228.32/32
- 52.204.230.227/32

And will I still need the CREATEROLE or SUPERUSER privilege?

**Comment by erinkcochran87** [comment]
Hi there @jrdnlowry, Stitch's support team is the best resource for troubleshooting any behavior or answering product questions. You can reach our support team through in-app chat or by emailing help@stitchdata.com.

If you have questions or feedback on the [Stitch Docs](https://www.stitchdata.com/docs), though, I'd be happy to assist!
