### ISSUE TITLE
Stitch with postgresql 9.6

### ISSUE THREAD

**Issue by sahsu** [stitchdata/docs#539]
Hi, 

According postgresql manual said you only need 
> https://www.stitchdata.com/docs/integrations/databases/postgresql/v1

```
host replication [account] [IP]   md5
```

to add into stitch but actually you do need
1. host `your_database_name` for tapping permission and
1. host replication for replication

I don't know what going with your support but this small problem used us 2 month to troubleshooting and support only answer please check the manual ( but which is total wrong from beginning. )

Please fix manual.

**Comment by erinkcochran87** [comment]
I'm going to close this for now, but I'll re-open if I hear anything else about this.
